fix

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 #this config file for set-up ssh and docker
-
+set -e #option that causes the script to exit immediately if any command returns a non-zero exit status 
 echo "Begin, you have to be sudo"
 
 sudo apt update -y && apt upgrade -y
@@ -9,11 +9,19 @@ sudo apt update -y && apt upgrade -y
 
 sudo apt install openssh-server -y
 
-echo "Port 22
-PermitRootLogin no
-PasswordAuthentication no
-PubkeyAuthentication yes
-" >>  /etc/ssh/sshd_config
+# the problem with port in macos
+
+# echo "Port 22
+# PermitRootLogin no
+# PasswordAuthentication no
+# PubkeyAuthentication yes
+# " >>  /etc/ssh/sshd_config
+
+sudo cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak
+sudo sed -i 's/#Port 22/Port 22/' /etc/ssh/sshd_config
+sudo sed -i 's/#PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config
+sudo sed -i 's/#PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config
+sudo sed -i 's/#PubkeyAuthentication.*/PubkeyAuthentication yes/' /etc/ssh/sshd_config
 
 sudo systemctl restart sshd
 
